# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token de47d3b2594dab309d6b7fb18a03db8fd842f219

{
  "title": "Лебедь",
  "description": "Бумажный"
}

###

# попытка поменять статус объявления
PATCH {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token de47d3b2594dab309d6b7fb18a03db8fd842f219

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-11-11
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

# проверка создания нового объявления после закрытия старого
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token de47d3b2594dab309d6b7fb18a03db8fd842f219

{
  "title": "Портфель",
  "description": "Кожаный"
}
