# Generated by Django 4.2 on 2023-04-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_user",
                        to="advertisements.advertisement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_adv",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advertisement",
            name="favourite",
            field=models.ManyToManyField(
                related_name="favourite",
                through="advertisements.Favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
