# Generated by Django 4.1.7 on 2023-04-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_scope_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
                verbose_name="Раздел",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="articles",
            field=models.ManyToManyField(
                related_name="tags",
                through="articles.Scope",
                to="articles.article",
                verbose_name="Статьи",
            ),
        ),
    ]
