# Generated by Django 4.1.7 on 2023-04-10 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_auto_20230410_0552"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
    ]
